### ISSUE TITLE
estimate_start_times dependency

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/batch-processing-analysis#1]
Hi @david-chapela, I can't find `estimate_start_times` to be declared as a dependency somewhere, but you import it in the code. 
https://github.com/AutomatedProcessImprovement/batch-processing-analysis/blob/08a0f25fc6d0459bcc41b017b4c46148e0c14959/src/batch_processing_analysis/batch_processing_analysis.py#L4

**Comment by david-chapela** [comment]
To be honest I'm not sure of how to add a dependency to a module that it's not published, because it won't install it automatically. But I made like SIMOD has, just added the dependency in the requirements.txt file, if there is another way just let me know!

**Comment by iharsuvorau** [comment]
You might want to try this: https://matiascodesal.com/blog/how-use-git-repository-pip-dependency/. I haven't tried it myself though, but used packages, incl. Simod, that depended on git-repositories. Not sure, pip installs them correctly, but we can try, or maybe it was just my experience.

Another way, is to add a git submodule to `external`. That's what I usually do. Then a user knows there's a dependency, and knows a specific commit that it depends on.
