### ISSUE TITLE
Package and module name conflict

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/batch-processing-analysis#2]
Hey, there is problem with importing `batch_processing_analysis.py` from the package `batch_processing_analysis`. My tests and dependent scripts crash. However, if I rename the fils of the modules:

- batch_processing_analysis.py → processing_analysis.py

and the rest of the modules for consistency:

- batch_processing_discovery.py → processing_discovery.py
- batch_processing_report.py → processing_report.py
- batch_activation_rules.py → activation_rules.py

— it works fine.

**Comment by david-chapela** [comment]
Should be fixed with the latest commit! Let me know if you have any other problem!

I renamed them to:
_analysis_, _discovery_ and _reporting_ because, as they are all inside the _batch_processing_analysis_ package, they don't need the "_processing_" or "_batch_" tag.
