### ISSUE TITLE
consider_parallelism is missing in estimate_start_times.config

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/batch-processing-analysis#3]
The parameter `consider_parallelism` seems like missing from https://github.com/AutomatedProcessImprovement/start-time-estimator/blob/main/src/estimate_start_times/config.py.

https://github.com/AutomatedProcessImprovement/batch-processing-analysis/blob/08a0f25fc6d0459bcc41b017b4c46148e0c14959/src/batch_processing_analysis/batch_processing_analysis.py#L37

It crashes the dependent software.

**Comment by david-chapela** [comment]
Yeah, I refactored the start time estimation so all of it can consider already recorded start times, so I changed the name to "consider_start_times" cause now it considers them not only for parallelism purposes.

I'll refactor also the batch project, so it doesn't crash.
